name: deployment to prod

on:
  pull_request:
    types: 
      - closed
    branches: [main]

jobs:
  lint:
    name: check lint
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v2
      - name: install dependencies
        run: |
        echo "Installing Next dependencies..."
        npm i

  test:
    name: run unit tests

  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    needs: [lint, test]

