name: deployment precheck

on:
  pull_request:
    types: 
      - opened
    branches: [dev]

jobs:
  lint:
    name: check lint
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: install dependencies
        run: npm ci
          
      - name: run lint
        run: npm run lint
          
        env:
          CI: true