name: deploypipline

on:
  merge:
    branches: [main]

jobs:
  lintTest:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          echo "Installing dependencies..."
          npm install 
      - name: Run lint
        run: |
          echo "Running linting test..."
          npm run lint
        env:
          CI: true