name: dev precheck

on:
  pull_request:
    types: 
      - opened
    branches: [dev]
jobs:
  lint:
    name: check lint
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v2
      - name: install dependencies
        run: echo "Installing Next dependencies..."
          
    